import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Proyecto modular",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="bg-gray-600 dark:bg-gray-900 font-sans">
          {children}
          <Footer />
        </section>
      </body>
    </html>
  );
}
